[package]
name = "fsc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rslnp = "0.2.1"
token-parser = "0.3.0"
argparse = "0.2.2"
